### ISSUE TITLE
do poprawy

### ISSUE THREAD

**Issue by michal-bootcamp** [JoannaKu/Java-Script-5#1]
- [x] jesli stosujesz sredniki na koncach linii, to zeby bylo spojnie stosuj je wszedzie (linie: 11, 15, 19, 23)
- [x] konwencja jest taka, zeby pisac bez spacji `console.log(...)`
- [x] kolejna konwencja jest taka, zeby blok if..else byl sformatowany w ten sposob:
```
if (value>0) {
    ...
} else if (value<0) {
    ...
}
```
- [x] dodaj wprowadzanie wartosci a i b przez `prompt`, bedzie mozna potestowac :)

**Comment by JoannaKu** [comment]
poprawione :)

**Comment by michal-bootcamp** [comment]
jak podam dwa zera, to dostaje informacje "zle podane wartosci"

**Comment by JoannaKu** [comment]
ok. usunęłam ostatni warunek. zostawiłam samo else. Teraz jest ok? :)

**Comment by michal-bootcamp** [comment]
teraz nie jest ok, poniewaz w zadaniu chodzi o to zeby wlasnie sprawdzic, czy wynik jest rowny zero. Teraz jak podam cos innego niz liczby dostaje info, ze "wynik rowny zero", a to nieprawda.
Wczesniej mialas ok, tylko warunek sprawdzania zera byl nieprawidlowy

**Comment by JoannaKu** [comment]
ok, wydaje mi się że zrozumiałam co było źle :)

**Comment by michal-bootcamp** [comment]
bardzo dobrze, dla poszerzenia wiedzy poczytaj o roznicy miedzy `==` i `===`
http://bonsaiden.github.io/JavaScript-Garden/pl/#types.equality
